version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "$DB_USER"
      POSTGRES_DB: "$DB_NAME"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
    ports:
      - "5432:5432"
    restart: unless-stopped
