version: "3"

services:
  # it gives database unkown error during 1 or 2 minutes after start
  db:
    image: postgis/postgis
    environment:
      POSTGRES_USER: "$DB_USER"
      POSTGRES_DB: "$DB_NAME"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      SSL: "$DB_SSL"
    ports:
      - "5432:5432"
    restart: unless-stopped
